name: Bug report
description: |
  Report unexpected behavior from Hermeto.
  For security vulnerabilities see "Report a security vulnerability" in the templates.
labels: ["bug"]
body:
  - type: textarea
    id: issue-description
    attributes:
      label: Describe the issue
    validations:
      required: true

  - type: textarea
    id: reproducer
    attributes:
      label: Steps to reproduce
      description: |
        A short example of steps needed to reproduce the issue.
        It should be self-contained and copy-pastable in a terminal.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Any tools and their versions that you believe to be relevant to the issue.

  - type: textarea
    id: impact
    attributes:
      label: How does this issue affect you or how did you find it
      description: |
        Please explain how this issue concretely affects you or others.
        Especially if it does not impact you how did you find it?
    validations:
      required: true
