name: Bug report
description: |
  Report unexpected behavior from Hermeto.
  For security vulnerabilities see "Report a security vulnerability" in the templates.
labels: ["bug"]
body:
  - type: textarea
    id: issue-description
    attributes:
      label: Describe the issue
    validations:
      required: true

  - type: textarea
    id: reproducer
    attributes:
      label: Steps to reproduce
      description: |
        Provide a short example of the steps needed to reproduce the issue.
        Make sure the issue is reproducible on the latest version in the main branch. 
        It should be self-contained and copy-pastable in a terminal.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        List your operating system and any other relevant tools together with their versions.

  - type: textarea
    id: impact
    attributes:
      label: How does this issue affect you or how did you find it
      description: |
        Explain how this issue affects you or others.
        If it does not directly impact you, how did you find it?
    validations:
      required: true
