name: Feature Request
description: |
  Thank you for your interest in improving Hermeto!

labels: ["enhancement"]
body:
  - type: textarea
    id: proposal
    attributes:
      label: "Proposed new feature or change:"
