name: Feature Request
description: Request a new feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Are you not sure whether the requested feature fits into Hermeto?
        Consider starting a [Discussion](https://github.com/orgs/hermetoproject/discussions) on GitHub.

  - type: textarea
    id: request
    attributes:
      label: "Requested new feature or change"
    validations:
      required: true
